version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URI=mongodb://mongo:27017/petshop
    depends_on:
      - mongo
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - petshop-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - petshop-network

networks:
  petshop-network:
    driver: bridge

volumes:
  mongo-data: