version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: client_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=cliente_db
      - API_V1_STR=/api/v1
      - SERVER_PORT=8000
      - DEBUG=True
      - SECRET_KEY=n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B
    depends_on:
      - mongo
    networks:
      - client-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:6
    container_name: client_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - client-network

  # Service for running tests 
  test:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: client_test
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=test_cliente_db
      - DEBUG=True
      - SECRET_KEY=test_secret_key
    depends_on:
      - mongo
    networks:
      - client-network
    command: pytest

networks:
  client-network:
    driver: bridge

volumes:
  mongo_data: