[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "client_management"
version = "0.1.0"
description = "FastAPI Client Management API"
readme = "README.md"

[tool.setuptools]
packages = ["app"]